targets:
  $default:
    builders:
      drift_dev:
        options:
          databases:
            app_database: lib/src/shared/data/database/app_database.dart
          schema_dir: drift_schemas/
          test_dir: test/database/migrations/
